name: Package
on:
  push:
    branches:
      - main
jobs:
  package:
    name: Package Easy Jobs PyPI
    runs-on: ubuntu-latest
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Packaging dependencies
        run: |
          pip install wheel twine

      - name: Package & Test PyPI Installation
        run: |
          export PYQL_NEXT_VER=$(pip -qqq download easyjobs && ls easyjobs*.whl | sed 's/-/" "/g' | awk '{print "(" $2 ")"}' |  python nextbuild.py)
          sed -i 's/PYQLVERSION/'$PYQL_NEXT_VER'/g' setup.py
          python setup.py bdist_wheel
          export PYQL_PACKAGE=$(pwd)/dist/easyjobs-$PYQL_NEXT_VER-py3-none-any.whl
          pip install $(echo -n $PYQL_PACKAGE)

      - name: Upload to PyPi
        env: # Or as an environment variable
          PYPI: ${{ secrets.PYPI }}
        run: |
          export PYQL_NEXT_VER=$(pip -qqq download easyjobs && ls easyjobs*.whl | sed 's/-/" "/g' | awk '{print "(" $2 ")"}' |  python nextbuild.py) 
          export PYQL_PACKAGE=$(pwd)/dist/easyjobs-$PYQL_NEXT_VER-py3-none-any.whl
          python -m twine upload $(pwd)/dist/easyjobs-$PYQL_NEXT_VER-py3-none-any.whl -u codemation -p $PYPI